# Generated by Django 3.2.4 on 2021-08-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnpps', '0002_alter_services_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='details',
            field=models.TextField(default='some_value', max_length=100),
        ),
    ]
