# Generated by Django 3.2.4 on 2021-08-10 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gnpps', '0006_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='pictures',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gnpps.services'),
        ),
    ]
