# Generated by Django 3.2.4 on 2021-08-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnpps', '0007_auto_20210810_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='picture1',
            field=models.ImageField(default='default.jpg', upload_to='img/%y'),
        ),
        migrations.AddField(
            model_name='services',
            name='picture2',
            field=models.ImageField(default='default.jpg', upload_to='img/%y'),
        ),
        migrations.AddField(
            model_name='services',
            name='picture3',
            field=models.ImageField(default='default.jpg', upload_to='img/%y'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
